name: Deploy Firebase Functions ğŸ”¥
on:
  push:
    paths:
      - 'functions/**'
    branches:
      - master

jobs:
  deploy_functions:
    name: Deploy Cloud Functions â˜.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2

      - name: Install Firebase CLI ğŸ”¥
        run: npm install -g firebase-tools

      - name: Deploy ğŸš€
        run: firebase deploy --only functions
